<header>
    <h2>Administration</h2>
</header>
<section>



    <div class="container">

        <nav>
            <a href="<?= buildUrl('/admin/post/new'); ?>" title="Modifier une partie">
                <i class="fas fa-plus-square"></i>Ajouter une partie
            </a>
        </nav>
        <table>
            <thead>
                <th scope="col">Titre</th>
                <th  class="action" scope="col">Actions</th>
            </thead>

            <tbody>
                <?php foreach ($posts as $post) : ?>
                    <tr>

                        <td><?= htmlspecialchars($post['title']); ?></td>

                        <td class="action">
                            <a href="<?= buildUrl('/admin/post/edit', ['id' => $post['id']]); ?>" title="Modifier l'article">
                                <i class="fas fa-pen-square"></i>
                            </a>
                            <a href="<?= buildUrl('/admin/post/delete', ['id' => $post['id']]); ?>" title="Supprimer l'article">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</section>