<!-- Navbar -->
<nav>

    <h4 class="logo">Rolly</h4>

    <ul class="navlink">
        <li>
            <a href="#">Home</a>
        </li>
        <li>
            <a href="#about">A propos</a>
        </li>
        <li>
            <a href="#jdr">Le JDR</a>
        </li>
    </ul>

</nav>
<!-- Navbar -->

<!-- formulaire login-->

<div class="container">


    <div class="form_login" id="signin">
        <h3 class="title_log">LogIn</h3>
        <form>
        <p id="connexion_error"></p>
            <div>
            <label for="pseudo">Pseudo</label>
                <input type="text" id="pseudo" name="pseudo" placeholder="Pseudo">
            </div>
            <div>
                <label for="email">Email</label>
                <input type="email" name="email" id="email" placeholder="Email" value="<?= isset($email) ? $email : ''; ?>">
            </div>

            <div>
                <label for="password">Mot de passe</label>
                <input type="password" id="mdp" name="password" placeholder="Mot de passe">
            </div>

            <div>

            <a href="<?= buildUrl('/post'); ?>">Connexion</a>
            <!--   <input type="submit" id="login_button" value="connexion">
                <button type="button" class="btn" href="<?= buildUrl('/show_post'); ?>" >Login</button> 
               
               
             <button class="btn" id="login_button" value="connexion" href="<?= buildUrl('/show_post'); ?>"> Connexion</button> -->
            </div>

        </form>

        <div>
            <img src="img/18.png" id="login_token">

        </div>

        <!--  <div>
        <span class="toggle"><a href="#signup">Pas encore membre ? Créer un compte</a></span>
    </div>
-->
    </div>

    <div class="form_login" id="signup">
        <h3 class="title_log">Sign up</h3>
        <form>
            

                <div>
                    <input type="text" name="pseudo" id="username" placeholder="Choisir un pseudo">
                    <label>pseudo</label>
                </div>

                <div>
                    <input type="text" name="email" placeholder="E-mail">
                    <label>e-mail</label>
                </div>
                <div>
                    <input type="password" name="password" placeholder="Mot de passe" autocomplete="new-password">
                    <label>password</label>
                </div>
                <div>
                    <input type="password" name="password2" placeholder="Re saisir le mot de passe" autocomplete="new-password">
                    <label>re-enter password</label>
                </div>
                <div>
                    <button type="submit" class="btn" id="login_button"> Envoyer </button>
                </div>

           
        </form>
    </div>

</div>

<div id="jdr">
<h3>Le JDR</h3>
<p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
     totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
      Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, 
      sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. 
      Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit,
       sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
        Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, 
        nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, 
    vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>
</div>
<div class="parallax">

</div>
<div id="about">
    <h3>A propos</h3>
<p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
     totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
      Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, 
      sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. 
      Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit,
       sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
        Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, 
        nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, 
    vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>
</div>

