<?php $cssItem = 'members2.css'; ?>

<div id="container" class="row col-8">
    <!--  BANNIERE DU HAUT-->
    <div id="banner" class="row col-12">

        <div class='col-8'>
            <h1>VOTRE ESPACE</h1>

            <div id="pseudo">
                <img class="square" src="https://1.bp.blogspot.com/-lr6rmgLGnX0/Xb9id7Y0kAI/AAAAAAAAA9Q/UJHKuLR9CI4Rjz2S5qB-dw6cJAUsB83awCLcBGAsYHQ/s1600/token%2Bmagotte.png" alt="avatar">
                <p>Pseudo:</p>

            </div>
            <div class="btn-group">
                <button type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Règles JDR (liens externes)
                </button>
                <div class="dropdown-menu ">
                    <button class="dropdown-item" type="button">D&D</button>
                    <button class="dropdown-item" type="button">Naheubleuk</button>
                    <button class="dropdown-item" type="button">???</button>
                </div>
            </div>
        </div>

        <div class="col-4" id="top_right">
            <button type="button" class="btn btn-danger" id="deconnexion">Se deconnecter</button>
        </div>

    </div>
    <!--  BANNIERE DU HAUT-->

    <div id="central" class="row col-12">

        <div id="gauche" class="col-8">
            
            <button type="button" class="btn btn-danger" id="new_game_button"> Créer nouvelle partie</button>
            <button type="button" id="aide" class="btn btn-info">Info</button>
            <h2 id="partie_title">PARTIES RECENTES</h2>
            <div id="partie">



                <div id="oneplay">
                    <?php foreach ($posts as $post) : ?>
                        <h3><?= htmlspecialchars($post['title']); ?></h3>
                    <?php endforeach; ?>
                </div>

            </div>
        </div>
        <div id="droite" class="col-4">


            <div class="col-12" id="galery">
                <h2>GALERY</h2>
            </div>

            <div class="col-12" id="map">
                <img class="round" src="img/map.png" alt="map">
            </div>

            <div class="col-12" id="musique">
                <img class="round" src="img/notes.png" alt="musique">
            </div>

            <div class="col-12" id="token">
                <img class="round" src="img/token.png" alt="token">
            </div>

        </div>

    </div>

</div>